name: New Release of Latex Document
on:
  push:
    branches:
      - 'main'

jobs:
  release_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          working_directory: resume/
          continue_on_error: true
      - name: Create Release     
        run: |
            echo "BUILD_DATE=$(date +'%d-%b-%Y')" >> $GITHUB_ENV
            echo "COMPLETE_BUILD_DATE=$(date +'%d-%b-%Y_%h-%mm-%s')" >> $GITHUB_ENV
            mv resume/main.pdf resume/resume.pdf
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ env.COMPLETE_BUILD_DATE }}"
          prerelease: false
          title: "Resume Version ${{ env.BUILD_DATE }}"
          files: |
            resume/resume.pdf
